### ISSUE TITLE
Need a good icon for the application

### ISSUE THREAD

**Issue by dilshankarunarathne** [Altier-Tech/directory-synchronizer#1]
ඇපයට අයිකනයක් අවශ්‍ය කර තිබේ! 😁
හොද නමකුත් යෝජනා කරන්න. මේ ඇප් එකෙන් කරන්නෙ, ක්ලවුඩ් සින්කින් ප්‍රොසෙස් එකක් වගේ එකක්.
අපේ ෆෝල්ඩර් එකක් සහ සමාන්තර ක්ලවුඩ් ෆෝල්ඩර් එකක් synchronized ව තියාගැනීම.

**Comment by dilshankarunarathne** [comment]
ඇපයට අයිකනයක් අවශ්‍ය කර තිබේ! 
හොද නමකුත් යෝජනා කරන්න. මේ ඇප් එකෙන් කරන්නෙ, ක්ලවුඩ් සින්කින් ප්‍රොසෙස් එකක් වගේ එකක්. 
අපේ ෆෝල්ඩර් එකක් සහ සමාන්තර ක්ලවුඩ් ෆෝල්ඩර් එකක් synchronized ව තියාගැනීම.

**Comment by thilinaDilshan1** [comment]
Directory Pool කියන නම කොහොමද ?

**Comment by thilinaDilshan1** [comment]
![Untitled design copy 2](https://user-images.githubusercontent.com/84640766/209556869-f15e980e-5c14-4dc1-ae2c-3bbd0eda1f11.png)

**Comment by AhanafVai** [comment]
For the app name, you could consider a name that reflects the sync or cloud aspect of the app, such as ```SyncCloud``` or ```CloudSync```. Alternatively, you could choose a name that conveys the idea of freedom or release, such as ```FreedomSync```

**Comment by dilshankarunarathne** [comment]
කවුද whotto Uber ට මෙතන පුප දෙන්න කිව්වෙ ? 😒
කාගෙද මූ ?

**Comment by dilshankarunarathne** [comment]
> Directory Pool කියන නම කොහොමද ?

ඇයි pool කියලා දාන්නෙ? විශේෂ හේතුවක් තියෙනවා ද?

**Comment by dilshankarunarathne** [comment]
> For the app name, you could consider a name that reflects the sync or cloud aspect of the app, such as `SyncCloud` or `CloudSync`. Alternatively, you could choose a name that conveys the idea of freedom or release, such as `FreedomSync`

Thank you for your insight @AhanafVai ❤️

**Comment by thilinaDilshan1** [comment]
> > Directory Pool කියන නම කොහොමද ?
> 
> ඇයි pool කියලා දාන්නෙ? විශේෂ හේතුවක් තියෙනවා ද?

අන්තිමට එතන නිකං directory collection එකක් වගේනෙ, ඒකයි😁
